name = "sius-ai-workshop"
pages_build_output_dir = "./dist"
compatibility_date = "2024-04-01"

[[kv_namespaces]]
binding = "SPX_MEMORY"
id = "d885526d2249419eaf921dcb7dd27488"

[[d1_databases]]
binding = "SPX_RECAP_DB"
database_name = "spx-recap-db"
database_id = "00a4729d-1792-42d1-bd86-ed58dfe1f95f"

[[d1_databases]]
binding = "MARKET_CACHE_DB"
database_name = "market-cache-db"
database_id = "c629da02-21ce-4b1c-87f2-59ba54be922e"

[[r2_buckets]]
binding = "VALUATION_DATA"
bucket_name = "valuation-watcher-data"

[[r2_buckets]]
binding = "MARKET_BREADTH_DATA"
bucket_name = "market-breadth-data"
